version: "3"
services:
    platformio:
        container_name: platformio
        build:
            context: ./dockerfiles/platformio
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
        stdin_open: true

    cquery:
        container_name: cquery
        build:
            context: ./dockerfiles/cquery
        depends_on:
            - platformio
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
        stdin_open: true

    docker-langserver:
        image: rcjsuen/docker-langserver
        volumes:
            - ./:/root/project_root
        stdin_open: true
        entrypoint: /bin/ash

    main:
        build:
            context: ./dockerfiles/neovim
            args:
                cmds: "motordriver2018_docker-langserver_1:/docker-langserver/bin/docker-langserver platformio:platformio cquery:cquery"
        depends_on:
            - cquery
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
            - /var/run/docker.sock:/var/run/docker.sock
            - ./coc-settings.json:/root/.config/nvim/coc-settings.json
        stdin_open: true
        working_dir: /root/project_root

volumes:
    platformio:
