version: "3"
services:
    platformio:
        image: platformio
        container_name: platformio
        build:
            context: ./dockerfiles/platformio
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
        stdin_open: true

    ccls:
        image: ccls
        container_name: ccls
        build:
            context: ./dockerfiles/ccls
        depends_on:
            - platformio
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
        stdin_open: true

    main:
        image: main
        build:
            context: ./dockerfiles/neovim
            args:
                cmds: "platformio:platformio ccls:ccls"
        depends_on:
            - ccls
        volumes:
            - ./:/root/project_root
            - platformio:/root/.platformio
            - /var/run/docker.sock:/var/run/docker.sock
            - ./coc-settings.json:/root/.config/nvim/coc-settings.json
        stdin_open: true
        working_dir: /root/project_root

volumes:
    platformio:
